#!/usr/bin/env bash
# Launches OceanMail Desktop's development spike: a Thunderbird instance
# running against an OceanMail-only profile, with the mandatory OceanMail
# extension loaded, isolated from the operator's normal Thunderbird profile
# and from any other Thunderbird installation on this machine.
#
# Isolation approach (see docs/decisions/0005-thunderbird-client-foundation.md,
# "OceanMail Desktop must coexist with stock Thunderbird"):
#   - runs with -no-remote -profile <isolated dir>, so it never attaches to
#     an already-running Thunderbird or touches ~/.thunderbird;
#   - all OceanMail-specific prefs/extension state live only inside that
#     profile directory (desktop/.dev-profile by default), never in the
#     shared Thunderbird binary or any other profile;
#   - the mandatory extension is loaded via a per-profile "extension proxy
#     file" pointing at desktop/extension/, so nothing is installed into the
#     shared Thunderbird binary's own distribution/extensions directory.
#
# This script deliberately does NOT use any system-installed/apt-packaged
# Thunderbird. It requires the pinned vendored copy fetched by
# fetch-thunderbird.sh (desktop/.vendor/, gitignored). OceanMail Desktop dev
# tooling must never launch or depend on the operator's own Thunderbird
# install, even with an isolated profile, so it can never affect that binary
# or its update state. See docs/THUNDERBIRD_BASELINE.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DESKTOP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
EXTENSION_DIR="$DESKTOP_DIR/extension"
PROFILE_DIR="${OCEANMAIL_DEV_PROFILE:-$DESKTOP_DIR/.dev-profile}"
EXTENSION_ID="oceanmail@oceanmail.dev"
PINNED_VERSION="140.14.0esr"
DEFAULT_THUNDERBIRD_BIN="$DESKTOP_DIR/.vendor/thunderbird-${PINNED_VERSION}/thunderbird/thunderbird"
THUNDERBIRD_BIN="${OCEANMAIL_THUNDERBIRD_BIN:-$DEFAULT_THUNDERBIRD_BIN}"

if [[ ! -x "$THUNDERBIRD_BIN" ]]; then
    echo "ERROR: pinned Thunderbird binary not found at $THUNDERBIRD_BIN" >&2
    echo "Run scripts/fetch-thunderbird.sh first. This script refuses to fall" >&2
    echo "back to any system-installed Thunderbird (see docs/THUNDERBIRD_BASELINE.md)." >&2
    exit 2
fi

mkdir -p "$PROFILE_DIR/extensions"

# Profile-scoped preferences only. Deliberately NOT policies.json: policies.json
# is installed at the machine/application level and would risk affecting a
# separately installed stock Thunderbird, which Decision 0005 explicitly
# forbids. user.js only affects this one profile directory.
#
# mail.accounthub.enabled, mail.provider.suppress_dialog_on_startup, and
# mail.chat.enabled were confirmed to exist in the installed Thunderbird
# 140.14.0esr build by inspecting its omni.ja (see
# docs/THUNDERBIRD_BASELINE.md) rather than assumed from memory.
#
# mail.chat.enabled=false (Decision 0007 cleanup, project-lead correction,
# PR #7 review: "hide the generic Chat destination for this alpha") is a
# real, documented Thunderbird preference — confirmed in
# chat/chat-messenger.js and preferences/preferences.js to hide the native
# Chat Spaces-toolbar button and its Preferences pane — not a DOM-mutation
# chrome hack. It is profile-scoped exactly like the others here, so this
# never affects a separately installed stock Thunderbird. No equivalent
# preference was found for hiding just the native Tasks Space without also
# hiding Calendar; see docs/MAIL_MODEL_CORRECTION.md for that documented
# gap rather than a new native-chrome bridge to force it.
cat > "$PROFILE_DIR/user.js" <<'PREFS'
// Generated by desktop/scripts/dev-launch.sh — profile-scoped only.
user_pref("mail.accounthub.enabled", false);
user_pref("mail.provider.suppress_dialog_on_startup", true);
user_pref("mail.chat.enabled", false);
// Allows loading the unpacked, unsigned OceanMail extension via the
// extension-proxy-file mechanism below. Scoped to this profile only; does
// not affect any other Thunderbird profile or installation.
user_pref("xpinstall.signatures.required", false);
user_pref("extensions.autoDisableScopes", 0);
PREFS

# Extension proxy file: a single line containing the absolute path to the
# unpacked extension. Thunderbird loads it directly from that path instead of
# copying it into the profile, so edits under extension/ take effect on next
# launch without reinstalling.
printf '%s' "$EXTENSION_DIR" > "$PROFILE_DIR/extensions/$EXTENSION_ID"

echo "Launching OceanMail Desktop dev spike"
echo "  Thunderbird binary: $(command -v "$THUNDERBIRD_BIN")"
echo "  Isolated profile:   $PROFILE_DIR"
echo "  Extension source:   $EXTENSION_DIR"

exec "$THUNDERBIRD_BIN" -no-remote -profile "$PROFILE_DIR" "$@"
